// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8K2E8rymcnaUxCo8saKPnq_fJLuJk2XY',
    appId: '1:505398063190:web:39f6c96e6ebca127c54bf7',
    messagingSenderId: '505398063190',
    projectId: 'fluttrer-ci-cd',
    authDomain: 'fluttrer-ci-cd.firebaseapp.com',
    storageBucket: 'fluttrer-ci-cd.firebasestorage.app',
    measurementId: 'G-020PZLM7TJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoZloJMyEm2dZbYpoPhLrQ7Uk2gTaW7Ho',
    appId: '1:505398063190:android:fbb8d6f965f14986c54bf7',
    messagingSenderId: '505398063190',
    projectId: 'fluttrer-ci-cd',
    storageBucket: 'fluttrer-ci-cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyZ58xEb915Y6Tn8CmqKOK4kaiVf-6eCg',
    appId: '1:505398063190:ios:6a3b0483e0afc75dc54bf7',
    messagingSenderId: '505398063190',
    projectId: 'fluttrer-ci-cd',
    storageBucket: 'fluttrer-ci-cd.firebasestorage.app',
    iosBundleId: 'com.example.flutterCiCd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyZ58xEb915Y6Tn8CmqKOK4kaiVf-6eCg',
    appId: '1:505398063190:ios:6a3b0483e0afc75dc54bf7',
    messagingSenderId: '505398063190',
    projectId: 'fluttrer-ci-cd',
    storageBucket: 'fluttrer-ci-cd.firebasestorage.app',
    iosBundleId: 'com.example.flutterCiCd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8K2E8rymcnaUxCo8saKPnq_fJLuJk2XY',
    appId: '1:505398063190:web:9f6061407a89e7c6c54bf7',
    messagingSenderId: '505398063190',
    projectId: 'fluttrer-ci-cd',
    authDomain: 'fluttrer-ci-cd.firebaseapp.com',
    storageBucket: 'fluttrer-ci-cd.firebasestorage.app',
    measurementId: 'G-PMJ7LPF18K',
  );
}
