
default_platform(:android)

platform :android do
  desc "Distribute app to firebase app distribution"
  lane :distribute do
    sh "flutter clean"
    sh "flutter build apk --release"
     firebase_app_distribution(
    app: "1:505398063190:android:fbb8d6f965f14986c54bf7",
    firebase_cli_token: ENV['firebase_cli_token'],
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/apk/release/app-release.apk",
    testers: "hossaaamahmed6@gmail.com",
    release_notes: "This is a test release for the app distribution",
  )
  end
end
